name: Python Style Checks

on:
  push:
    branches:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Run Black formatter check
      run: |
        black --check .

    - name: Run Flake8 style check
      run: |
        flake8 .
